receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'din-prometheus-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['din-caddy:2019'] ##TODO: Needs to be updated with the actual docker container name

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging]