// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package prometheus is a generated GoMock package.
package prometheus

import (
	reflect "reflect"
	time "time"

	http "github.com/DIN-center/din-caddy-plugins/lib/http"
	gomock "github.com/golang/mock/gomock"
)

// MockIPrometheusClient is a mock of IPrometheusClient interface.
type MockIPrometheusClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPrometheusClientMockRecorder
}

// MockIPrometheusClientMockRecorder is the mock recorder for MockIPrometheusClient.
type MockIPrometheusClientMockRecorder struct {
	mock *MockIPrometheusClient
}

// NewMockIPrometheusClient creates a new mock instance.
func NewMockIPrometheusClient(ctrl *gomock.Controller) *MockIPrometheusClient {
	mock := &MockIPrometheusClient{ctrl: ctrl}
	mock.recorder = &MockIPrometheusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPrometheusClient) EXPECT() *MockIPrometheusClientMockRecorder {
	return m.recorder
}

// HandleHealthCheckMetric mocks base method.
func (m *MockIPrometheusClient) HandleHealthCheckMetric(data *PromHealthCheckMetricData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleHealthCheckMetric", data)
}

// HandleHealthCheckMetric indicates an expected call of HandleHealthCheckMetric.
func (mr *MockIPrometheusClientMockRecorder) HandleHealthCheckMetric(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleHealthCheckMetric", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleHealthCheckMetric), data)
}

// HandleNetworkHealthCheckMetric mocks base method.
func (m *MockIPrometheusClient) HandleNetworkHealthCheckMetric(data *PromNetworkHealthCheckMetricData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleNetworkHealthCheckMetric", data)
}

// HandleNetworkHealthCheckMetric indicates an expected call of HandleNetworkHealthCheckMetric.
func (mr *MockIPrometheusClientMockRecorder) HandleNetworkHealthCheckMetric(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNetworkHealthCheckMetric", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleNetworkHealthCheckMetric), data)
}

// HandleRequestMetrics mocks base method.
func (m *MockIPrometheusClient) HandleRequestMetrics(data *PromRequestMetricData, duration time.Duration, requestBody *http.JSONRPCRequest) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRequestMetrics", data, duration, requestBody)
}

// HandleRequestMetrics indicates an expected call of HandleRequestMetrics.
func (mr *MockIPrometheusClientMockRecorder) HandleRequestMetrics(data, duration, requestBody interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequestMetrics", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleRequestMetrics), data, duration, requestBody)
}
