// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/prometheus/interface.go
//
// Generated by this command:
//
//	mockgen -source=./lib/prometheus/interface.go -package=prometheus -destination=./lib/prometheus/interface_mock.go
//

// Package prometheus is a generated GoMock package.
package prometheus

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIPrometheusClient is a mock of IPrometheusClient interface.
type MockIPrometheusClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPrometheusClientMockRecorder
	isgomock struct{}
}

// MockIPrometheusClientMockRecorder is the mock recorder for MockIPrometheusClient.
type MockIPrometheusClientMockRecorder struct {
	mock *MockIPrometheusClient
}

// NewMockIPrometheusClient creates a new mock instance.
func NewMockIPrometheusClient(ctrl *gomock.Controller) *MockIPrometheusClient {
	mock := &MockIPrometheusClient{ctrl: ctrl}
	mock.recorder = &MockIPrometheusClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPrometheusClient) EXPECT() *MockIPrometheusClientMockRecorder {
	return m.recorder
}

// HandleHealthCheckMetric mocks base method.
func (m *MockIPrometheusClient) HandleHealthCheckMetric(data *PromHealthCheckMetricData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleHealthCheckMetric", data)
}

// HandleHealthCheckMetric indicates an expected call of HandleHealthCheckMetric.
func (mr *MockIPrometheusClientMockRecorder) HandleHealthCheckMetric(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleHealthCheckMetric", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleHealthCheckMetric), data)
}

// HandleNetworkHealthCheckMetric mocks base method.
func (m *MockIPrometheusClient) HandleNetworkHealthCheckMetric(data *PromNetworkHealthCheckMetricData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleNetworkHealthCheckMetric", data)
}

// HandleNetworkHealthCheckMetric indicates an expected call of HandleNetworkHealthCheckMetric.
func (mr *MockIPrometheusClientMockRecorder) HandleNetworkHealthCheckMetric(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleNetworkHealthCheckMetric", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleNetworkHealthCheckMetric), data)
}

// HandleRequestMetrics mocks base method.
func (m *MockIPrometheusClient) HandleRequestMetrics(data *PromRequestMetricData, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRequestMetrics", data, duration)
}

// HandleRequestMetrics indicates an expected call of HandleRequestMetrics.
func (mr *MockIPrometheusClientMockRecorder) HandleRequestMetrics(data, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRequestMetrics", reflect.TypeOf((*MockIPrometheusClient)(nil).HandleRequestMetrics), data, duration)
}
