## This file is for local development purposes ONLY ##
version: '3.7'
services:
  din-caddy:
    image: din-caddy
    container_name: din-caddy
    restart: always
    ports:
      - 2019:2019
      - 8000:8000
    volumes:
      - ./Caddyfile.private:/etc/caddy/Caddyfile
  otel-collector:
    image: otel/opentelemetry-collector:0.99.0
    volumes:
      - ./services/open-telemetry/config.yml:/etc/otel/config/config.yml
    ports:
      - 4317:4317 # OpenTelemetry gRPC
      - 55679:55679 # trace spans panel
    command: ["--config=/etc/otel/config/config.yml"]