## This file is for local development purposes ONLY ##
version: '3.7'
services:
  din-caddy:
    image: din-caddy
    container_name: din-caddy
    restart: always
    ports:
      - 2019:2019
      - 8000:8000
    volumes:
      - ./Caddyfile.private:/etc/caddy/Caddyfile
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.99.0
    volumes:
      - ./services/otel-collector/config.yml:/etc/otel/config/config.yml
    ports:
      - 4317:4317 # OpenTelemetry gRPC
      - 9090:9090
      - 443:443
      - 8443:8443
      - 80:80
      - 55679:55679 # trace spans panel
    command: ["--config=/etc/otel/config/config.yml"]