### This file is for LOCAL development purposes ONLY ###
version: '3.7'

# Define custom networks
networks:
  din-network:
    driver: bridge

# for local development
services:
  din-caddy-server1:
    image: localhost/din-caddy
    container_name: din-caddy-server1
    restart: always
    networks:
      - din-network
    ports:
      - 8001:8000
    volumes:
      - ./Caddyfile.private:/etc/caddy/Caddyfile
      - ./caddy-data-server1:/srv
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    environment:
      - ENV=dev
  din-caddy-server2:
    image: localhost/din-caddy
    container_name: din-caddy-server2
    restart: always
    networks:
      - din-network
    ports:
      - 8002:8000
    volumes:
      - ./Caddyfile.private:/etc/caddy/Caddyfile
      - ./caddy-data-server2:/srv
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    environment:
      - ENV=dev
  gor:
    image: edaubert/goreplay:1.3.3
    container_name: gor
    restart: always
    network_mode: host  # Use host network to capture all traffic on host interfaces
    #command: --input-raw :8001 --output-http="http://localhost:8002" --output-http-timeout 30s
    command: --input-raw :8001 --output-stdout
    environment:
      - ENV=dev

