{
 "title": "DIN Overview Dashboard",
 "tags": [
  "din",
  "monitoring"
 ],
 "time": { "from": "2025-04-21T13:56:21.119Z", "to": "2025-04-21T14:34:39.640Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "query": "test,dev,prod" },
   {
    "name": "network",
    "query": {
     "query": "label_values(din_http_request_count, service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count by Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(service) (increase(din_http_request_count{service=~\"$network\",environment=~\"$env\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Count by Network + Provider",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(service, provider) (increase(din_http_request_count{service=~\"$network\", environment=~\"$env\"}[5m]))",
     "legendFormat": "{{service}} {{provider}}"
    }
   ]
  },
  {
   "title": "Errors Overview by Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(service) (increase(din_http_request_count{service=~\"$network\", environment=~\"$env\", response_status!=\"200\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total requests (1 hour)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(din_http_request_count{service=~\"$network\", environment=~\"$env\"}[1h])))"
    }
   ]
  },
  {
   "title": "Average Request Duration in Milliseconds",
   "type": "timeseries",
   "description": "This is based on data derived from the requests made by the customers/users of the din router.",
   "gridPos": { "h": 11, "w": 15, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(service, provider) (rate(din_http_request_duration_milliseconds_sum{service=~\"$network\", environment=~\"$env\"}[5m])) / sum by(service, provider) (rate(din_http_request_duration_milliseconds_count{service=~\"$network\", environment=~\"$env\"}[5m]))",
     "legendFormat": "{{service}} {{provider}}"
    }
   ]
  },
  {
   "title": "Total requests (1 day)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(din_http_request_count{service=~\"$network\", environment=~\"$env\"}[24h])))"
    }
   ]
  },
  {
   "title": "Request Distribution by Network",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (din_http_request_count{environment=~\"$env\"})",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Method count Overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(method) (increase(din_http_request_count{service=~\"$network\", environment=~\"$env\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Block Number (Filter to 1 network)",
   "type": "timeseries",
   "description": "Needs to be filtered to just 1 network for the data to make sense",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "max_over_time(din_health_check_block_number{service=~\"$network\", environment=~\"$env\"}[$__interval]) > 0",
     "legendFormat": "{{provider}}"
    }
   ]
  }
 ]
}