{
 "title": "DIN Health Check Dashboard",
 "tags": [
  "din",
  "health",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "env", "query": "test,beta,dev,prod" },
   { "name": "network", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  {
   "title": "Recent Health Check Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"din-caddy\"} | json | attributes_environment=\"$env\" and attributes_network=\"$network\" | attributes_level!=\"info\" and attributes_level!=\"debug\""
    }
   ]
  },
  {
   "title": "Recent Health Check Logs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(attributes_network) (count_over_time({job=\"din-caddy\"} | json [5m]))",
     "legendFormat": "{{attributes_network}}"
    }
   ]
  },
  {
   "title": "Health Check Logs by provider",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(attributes_network, attributes_provider) (count_over_time({job=\"din-caddy\"} | json [5m]))",
     "legendFormat": "{{attributes_network}} {{attributes_provider}}"
    }
   ]
  },
  {
   "title": "Health Check Logs by provider",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(provider, network) (din_http_request_count_total{environment=\"$env\", service=~\"$network\", response_status!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status by customer request metric",
   "type": "timeseries",
   "description": "to debug: set WHERE service = {network_name}",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by (service, provider, health_status) (increase(din_http_request_count_total{service=~\"$network\", environment=~\"$env\"}[5m]))",
     "legendFormat": "{{service}} {{provider}} {{health_status}}"
    }
   ]
  },
  {
   "title": "Health Status by health check metric",
   "type": "timeseries",
   "description": "to debug: set WHERE service = {network_name}",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (service, provider, health_status) (increase(din_health_check_count_total{service=~\"$network\", environment=~\"$env\"}[5m]))",
     "legendFormat": "{{service}} {{provider}} {{health_status}}"
    }
   ]
  }
 ]
}