// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/network/handlers.go
//
// Generated by this command:
//
//	mockgen -source=./lib/network/handlers.go -package=network -destination=./lib/network/interface_mock.go
//

// Package network is a generated GoMock package.
package network

import (
	http0 "net/http"
	reflect "reflect"

	auth "github.com/DIN-center/din-caddy-plugins/lib/auth"
	http "github.com/DIN-center/din-caddy-plugins/lib/http"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkHandler is a mock of NetworkHandler interface.
type MockNetworkHandler struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkHandlerMockRecorder
	isgomock struct{}
}

// MockNetworkHandlerMockRecorder is the mock recorder for MockNetworkHandler.
type MockNetworkHandlerMockRecorder struct {
	mock *MockNetworkHandler
}

// NewMockNetworkHandler creates a new mock instance.
func NewMockNetworkHandler(ctrl *gomock.Controller) *MockNetworkHandler {
	mock := &MockNetworkHandler{ctrl: ctrl}
	mock.recorder = &MockNetworkHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkHandler) EXPECT() *MockNetworkHandlerMockRecorder {
	return m.recorder
}

// ConfigureRequestPath mocks base method.
func (m *MockNetworkHandler) ConfigureRequestPath(req *http0.Request, providerPath, providerQuery, networkName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureRequestPath", req, providerPath, providerQuery, networkName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureRequestPath indicates an expected call of ConfigureRequestPath.
func (mr *MockNetworkHandlerMockRecorder) ConfigureRequestPath(req, providerPath, providerQuery, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureRequestPath", reflect.TypeOf((*MockNetworkHandler)(nil).ConfigureRequestPath), req, providerPath, providerQuery, networkName)
}

// CreateArchivePayload mocks base method.
func (m *MockNetworkHandler) CreateArchivePayload(method, blockHeight string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateArchivePayload", method, blockHeight)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateArchivePayload indicates an expected call of CreateArchivePayload.
func (mr *MockNetworkHandlerMockRecorder) CreateArchivePayload(method, blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateArchivePayload", reflect.TypeOf((*MockNetworkHandler)(nil).CreateArchivePayload), method, blockHeight)
}

// CreateBlockRequest mocks base method.
func (m *MockNetworkHandler) CreateBlockRequest(method string, blockNum int64, includeTransactions bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlockRequest", method, blockNum, includeTransactions)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlockRequest indicates an expected call of CreateBlockRequest.
func (mr *MockNetworkHandlerMockRecorder) CreateBlockRequest(method, blockNum, includeTransactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlockRequest", reflect.TypeOf((*MockNetworkHandler)(nil).CreateBlockRequest), method, blockNum, includeTransactions)
}

// CreateHealthCheckPayload mocks base method.
func (m *MockNetworkHandler) CreateHealthCheckPayload(method string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHealthCheckPayload", method)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHealthCheckPayload indicates an expected call of CreateHealthCheckPayload.
func (mr *MockNetworkHandlerMockRecorder) CreateHealthCheckPayload(method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHealthCheckPayload", reflect.TypeOf((*MockNetworkHandler)(nil).CreateHealthCheckPayload), method)
}

// ExtractBlockHash mocks base method.
func (m *MockNetworkHandler) ExtractBlockHash(blockData any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractBlockHash", blockData)
	ret0, _ := ret[0].(string)
	return ret0
}

// ExtractBlockHash indicates an expected call of ExtractBlockHash.
func (mr *MockNetworkHandlerMockRecorder) ExtractBlockHash(blockData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractBlockHash", reflect.TypeOf((*MockNetworkHandler)(nil).ExtractBlockHash), blockData)
}

// ExtractMethod mocks base method.
func (m *MockNetworkHandler) ExtractMethod(req *http0.Request, body []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractMethod", req, body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractMethod indicates an expected call of ExtractMethod.
func (mr *MockNetworkHandlerMockRecorder) ExtractMethod(req, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractMethod", reflect.TypeOf((*MockNetworkHandler)(nil).ExtractMethod), req, body)
}

// FormatBlockHeight mocks base method.
func (m *MockNetworkHandler) FormatBlockHeight(blockNum int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatBlockHeight", blockNum)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatBlockHeight indicates an expected call of FormatBlockHeight.
func (mr *MockNetworkHandlerMockRecorder) FormatBlockHeight(blockNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatBlockHeight", reflect.TypeOf((*MockNetworkHandler)(nil).FormatBlockHeight), blockNum)
}

// GetArchiveMethod mocks base method.
func (m *MockNetworkHandler) GetArchiveMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchiveMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetArchiveMethod indicates an expected call of GetArchiveMethod.
func (mr *MockNetworkHandlerMockRecorder) GetArchiveMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchiveMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetArchiveMethod))
}

// GetBlockByNumberMethod mocks base method.
func (m *MockNetworkHandler) GetBlockByNumberMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByNumberMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBlockByNumberMethod indicates an expected call of GetBlockByNumberMethod.
func (mr *MockNetworkHandlerMockRecorder) GetBlockByNumberMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByNumberMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetBlockByNumberMethod))
}

// GetBlockInfoMethod mocks base method.
func (m *MockNetworkHandler) GetBlockInfoMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockInfoMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBlockInfoMethod indicates an expected call of GetBlockInfoMethod.
func (mr *MockNetworkHandlerMockRecorder) GetBlockInfoMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockInfoMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetBlockInfoMethod))
}

// GetBlockTimestamp mocks base method.
func (m *MockNetworkHandler) GetBlockTimestamp(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int, blockNumber int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockTimestamp", httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockTimestamp indicates an expected call of GetBlockTimestamp.
func (mr *MockNetworkHandlerMockRecorder) GetBlockTimestamp(httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockTimestamp", reflect.TypeOf((*MockNetworkHandler)(nil).GetBlockTimestamp), httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber)
}

// GetChainID mocks base method.
func (m *MockNetworkHandler) GetChainID(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainID", httpUrl, headers, httpClient, authClient, requestAttempts)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChainID indicates an expected call of GetChainID.
func (mr *MockNetworkHandlerMockRecorder) GetChainID(httpUrl, headers, httpClient, authClient, requestAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainID", reflect.TypeOf((*MockNetworkHandler)(nil).GetChainID), httpUrl, headers, httpClient, authClient, requestAttempts)
}

// GetChainIDMethod mocks base method.
func (m *MockNetworkHandler) GetChainIDMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChainIDMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetChainIDMethod indicates an expected call of GetChainIDMethod.
func (mr *MockNetworkHandlerMockRecorder) GetChainIDMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChainIDMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetChainIDMethod))
}

// GetHealthCheckHTTPMethod mocks base method.
func (m *MockNetworkHandler) GetHealthCheckHTTPMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthCheckHTTPMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHealthCheckHTTPMethod indicates an expected call of GetHealthCheckHTTPMethod.
func (mr *MockNetworkHandlerMockRecorder) GetHealthCheckHTTPMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthCheckHTTPMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetHealthCheckHTTPMethod))
}

// GetHealthCheckMethod mocks base method.
func (m *MockNetworkHandler) GetHealthCheckMethod() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHealthCheckMethod")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHealthCheckMethod indicates an expected call of GetHealthCheckMethod.
func (mr *MockNetworkHandlerMockRecorder) GetHealthCheckMethod() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthCheckMethod", reflect.TypeOf((*MockNetworkHandler)(nil).GetHealthCheckMethod))
}

// GetLatestBlockNumber mocks base method.
func (m *MockNetworkHandler) GetLatestBlockNumber(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int) (*LatestBlockResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlockNumber", httpUrl, headers, httpClient, authClient, requestAttempts)
	ret0, _ := ret[0].(*LatestBlockResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockNumber indicates an expected call of GetLatestBlockNumber.
func (mr *MockNetworkHandlerMockRecorder) GetLatestBlockNumber(httpUrl, headers, httpClient, authClient, requestAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockNumber", reflect.TypeOf((*MockNetworkHandler)(nil).GetLatestBlockNumber), httpUrl, headers, httpClient, authClient, requestAttempts)
}

// GetName mocks base method.
func (m *MockNetworkHandler) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockNetworkHandlerMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockNetworkHandler)(nil).GetName))
}

// GetRequestType mocks base method.
func (m *MockNetworkHandler) GetRequestType() RequestType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestType")
	ret0, _ := ret[0].(RequestType)
	return ret0
}

// GetRequestType indicates an expected call of GetRequestType.
func (mr *MockNetworkHandlerMockRecorder) GetRequestType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestType", reflect.TypeOf((*MockNetworkHandler)(nil).GetRequestType))
}

// GetSupportedMethods mocks base method.
func (m *MockNetworkHandler) GetSupportedMethods() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedMethods")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetSupportedMethods indicates an expected call of GetSupportedMethods.
func (mr *MockNetworkHandlerMockRecorder) GetSupportedMethods() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedMethods", reflect.TypeOf((*MockNetworkHandler)(nil).GetSupportedMethods))
}

// GetType mocks base method.
func (m *MockNetworkHandler) GetType() HandlerType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(HandlerType)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockNetworkHandlerMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockNetworkHandler)(nil).GetType))
}

// Initialize mocks base method.
func (m *MockNetworkHandler) Initialize(config *NetworkConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockNetworkHandlerMockRecorder) Initialize(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockNetworkHandler)(nil).Initialize), config)
}

// IsRetryableError mocks base method.
func (m *MockNetworkHandler) IsRetryableError(err error, statusCode int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRetryableError", err, statusCode)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRetryableError indicates an expected call of IsRetryableError.
func (mr *MockNetworkHandlerMockRecorder) IsRetryableError(err, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRetryableError", reflect.TypeOf((*MockNetworkHandler)(nil).IsRetryableError), err, statusCode)
}

// IsRetryableOnDifferentProvider mocks base method.
func (m *MockNetworkHandler) IsRetryableOnDifferentProvider(err error, statusCode int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRetryableOnDifferentProvider", err, statusCode)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRetryableOnDifferentProvider indicates an expected call of IsRetryableOnDifferentProvider.
func (mr *MockNetworkHandlerMockRecorder) IsRetryableOnDifferentProvider(err, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRetryableOnDifferentProvider", reflect.TypeOf((*MockNetworkHandler)(nil).IsRetryableOnDifferentProvider), err, statusCode)
}

// ParseArchiveResponse mocks base method.
func (m *MockNetworkHandler) ParseArchiveResponse(body []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseArchiveResponse", body)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseArchiveResponse indicates an expected call of ParseArchiveResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseArchiveResponse(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseArchiveResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseArchiveResponse), body)
}

// ParseBlockNumberResponse mocks base method.
func (m *MockNetworkHandler) ParseBlockNumberResponse(body []byte, statusCode int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBlockNumberResponse", body, statusCode)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBlockNumberResponse indicates an expected call of ParseBlockNumberResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseBlockNumberResponse(body, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBlockNumberResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseBlockNumberResponse), body, statusCode)
}

// ParseBlockResponse mocks base method.
func (m *MockNetworkHandler) ParseBlockResponse(body []byte) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBlockResponse", body)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBlockResponse indicates an expected call of ParseBlockResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseBlockResponse(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBlockResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseBlockResponse), body)
}

// ParseChainIDResponse mocks base method.
func (m *MockNetworkHandler) ParseChainIDResponse(body []byte, statusCode int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseChainIDResponse", body, statusCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseChainIDResponse indicates an expected call of ParseChainIDResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseChainIDResponse(body, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseChainIDResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseChainIDResponse), body, statusCode)
}

// ParseHealthCheckResponse mocks base method.
func (m *MockNetworkHandler) ParseHealthCheckResponse(body []byte) (*BlockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseHealthCheckResponse", body)
	ret0, _ := ret[0].(*BlockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseHealthCheckResponse indicates an expected call of ParseHealthCheckResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseHealthCheckResponse(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseHealthCheckResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseHealthCheckResponse), body)
}

// ParseResponse mocks base method.
func (m *MockNetworkHandler) ParseResponse(body []byte, statusCode int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseResponse", body, statusCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParseResponse indicates an expected call of ParseResponse.
func (mr *MockNetworkHandlerMockRecorder) ParseResponse(body, statusCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseResponse", reflect.TypeOf((*MockNetworkHandler)(nil).ParseResponse), body, statusCode)
}

// PerformArchiveCheck mocks base method.
func (m *MockNetworkHandler) PerformArchiveCheck(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int, blockHeight string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformArchiveCheck", httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformArchiveCheck indicates an expected call of PerformArchiveCheck.
func (mr *MockNetworkHandlerMockRecorder) PerformArchiveCheck(httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformArchiveCheck", reflect.TypeOf((*MockNetworkHandler)(nil).PerformArchiveCheck), httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight)
}

// PerformGetBlockByNumber mocks base method.
func (m *MockNetworkHandler) PerformGetBlockByNumber(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int, blockNumber int64) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformGetBlockByNumber", httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PerformGetBlockByNumber indicates an expected call of PerformGetBlockByNumber.
func (mr *MockNetworkHandlerMockRecorder) PerformGetBlockByNumber(httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformGetBlockByNumber", reflect.TypeOf((*MockNetworkHandler)(nil).PerformGetBlockByNumber), httpUrl, headers, httpClient, authClient, requestAttempts, blockNumber)
}

// ProcessRequest mocks base method.
func (m *MockNetworkHandler) ProcessRequest(req *http0.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessRequest indicates an expected call of ProcessRequest.
func (mr *MockNetworkHandlerMockRecorder) ProcessRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRequest", reflect.TypeOf((*MockNetworkHandler)(nil).ProcessRequest), req)
}

// RequiresSeparateBlockInfoCall mocks base method.
func (m *MockNetworkHandler) RequiresSeparateBlockInfoCall() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresSeparateBlockInfoCall")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RequiresSeparateBlockInfoCall indicates an expected call of RequiresSeparateBlockInfoCall.
func (mr *MockNetworkHandlerMockRecorder) RequiresSeparateBlockInfoCall() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresSeparateBlockInfoCall", reflect.TypeOf((*MockNetworkHandler)(nil).RequiresSeparateBlockInfoCall))
}

// SupportsArchiveMode mocks base method.
func (m *MockNetworkHandler) SupportsArchiveMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsArchiveMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsArchiveMode indicates an expected call of SupportsArchiveMode.
func (mr *MockNetworkHandlerMockRecorder) SupportsArchiveMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsArchiveMode", reflect.TypeOf((*MockNetworkHandler)(nil).SupportsArchiveMode))
}

// SupportsDynamicBlockLag mocks base method.
func (m *MockNetworkHandler) SupportsDynamicBlockLag() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsDynamicBlockLag")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsDynamicBlockLag indicates an expected call of SupportsDynamicBlockLag.
func (mr *MockNetworkHandlerMockRecorder) SupportsDynamicBlockLag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsDynamicBlockLag", reflect.TypeOf((*MockNetworkHandler)(nil).SupportsDynamicBlockLag))
}

// SupportsGetBlockByNumber mocks base method.
func (m *MockNetworkHandler) SupportsGetBlockByNumber() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsGetBlockByNumber")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsGetBlockByNumber indicates an expected call of SupportsGetBlockByNumber.
func (mr *MockNetworkHandlerMockRecorder) SupportsGetBlockByNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsGetBlockByNumber", reflect.TypeOf((*MockNetworkHandler)(nil).SupportsGetBlockByNumber))
}

// ValidateChainID mocks base method.
func (m *MockNetworkHandler) ValidateChainID(chainID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateChainID", chainID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateChainID indicates an expected call of ValidateChainID.
func (mr *MockNetworkHandlerMockRecorder) ValidateChainID(chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateChainID", reflect.TypeOf((*MockNetworkHandler)(nil).ValidateChainID), chainID)
}

// MockTraceChecker is a mock of TraceChecker interface.
type MockTraceChecker struct {
	ctrl     *gomock.Controller
	recorder *MockTraceCheckerMockRecorder
	isgomock struct{}
}

// MockTraceCheckerMockRecorder is the mock recorder for MockTraceChecker.
type MockTraceCheckerMockRecorder struct {
	mock *MockTraceChecker
}

// NewMockTraceChecker creates a new mock instance.
func NewMockTraceChecker(ctrl *gomock.Controller) *MockTraceChecker {
	mock := &MockTraceChecker{ctrl: ctrl}
	mock.recorder = &MockTraceCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTraceChecker) EXPECT() *MockTraceCheckerMockRecorder {
	return m.recorder
}

// PerformTraceBlockByNumberCheck mocks base method.
func (m *MockTraceChecker) PerformTraceBlockByNumberCheck(httpUrl string, headers map[string]string, httpClient http.IHTTPClient, authClient auth.IAuthClient, requestAttempts int, blockHeight string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformTraceBlockByNumberCheck", httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformTraceBlockByNumberCheck indicates an expected call of PerformTraceBlockByNumberCheck.
func (mr *MockTraceCheckerMockRecorder) PerformTraceBlockByNumberCheck(httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformTraceBlockByNumberCheck", reflect.TypeOf((*MockTraceChecker)(nil).PerformTraceBlockByNumberCheck), httpUrl, headers, httpClient, authClient, requestAttempts, blockHeight)
}
