// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/watcher/interface.go
//
// Generated by this command:
//
//	mockgen -source=./lib/watcher/interface.go -package=watcher -destination=./lib/watcher/interface_mock.go
//

// Package watcher is a generated GoMock package.
package watcher

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIWatcherAPIClient is a mock of IWatcherAPIClient interface.
type MockIWatcherAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIWatcherAPIClientMockRecorder
	isgomock struct{}
}

// MockIWatcherAPIClientMockRecorder is the mock recorder for MockIWatcherAPIClient.
type MockIWatcherAPIClientMockRecorder struct {
	mock *MockIWatcherAPIClient
}

// NewMockIWatcherAPIClient creates a new mock instance.
func NewMockIWatcherAPIClient(ctrl *gomock.Controller) *MockIWatcherAPIClient {
	mock := &MockIWatcherAPIClient{ctrl: ctrl}
	mock.recorder = &MockIWatcherAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWatcherAPIClient) EXPECT() *MockIWatcherAPIClientMockRecorder {
	return m.recorder
}

// GetCheck mocks base method.
func (m *MockIWatcherAPIClient) GetCheck(params CheckQueryParams) Result[CheckResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCheck", params)
	ret0, _ := ret[0].(Result[CheckResponse])
	return ret0
}

// GetCheck indicates an expected call of GetCheck.
func (mr *MockIWatcherAPIClientMockRecorder) GetCheck(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCheck", reflect.TypeOf((*MockIWatcherAPIClient)(nil).GetCheck), params)
}

// GetLatency mocks base method.
func (m *MockIWatcherAPIClient) GetLatency(params LatencyQueryParams) Result[LatencyResponse] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatency", params)
	ret0, _ := ret[0].(Result[LatencyResponse])
	return ret0
}

// GetLatency indicates an expected call of GetLatency.
func (mr *MockIWatcherAPIClientMockRecorder) GetLatency(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatency", reflect.TypeOf((*MockIWatcherAPIClient)(nil).GetLatency), params)
}
