// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/din/interface.go
//
// Generated by this command:
//
//	mockgen -source=./lib/din/interface.go -package=din -destination=./lib/din/interface_mock.go
//

// Package din is a generated GoMock package.
package din

import (
	reflect "reflect"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	ethclient "github.com/ethereum/go-ethereum/ethclient"
	gomock "go.uber.org/mock/gomock"
)

// MockIDinClient is a mock of IDinClient interface.
type MockIDinClient struct {
	ctrl     *gomock.Controller
	recorder *MockIDinClientMockRecorder
	isgomock struct{}
}

// MockIDinClientMockRecorder is the mock recorder for MockIDinClient.
type MockIDinClientMockRecorder struct {
	mock *MockIDinClient
}

// NewMockIDinClient creates a new mock instance.
func NewMockIDinClient(ctrl *gomock.Controller) *MockIDinClient {
	mock := &MockIDinClient{ctrl: ctrl}
	mock.recorder = &MockIDinClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDinClient) EXPECT() *MockIDinClientMockRecorder {
	return m.recorder
}

// CreateAuthorizedTransactor mocks base method.
func (m *MockIDinClient) CreateAuthorizedTransactor(keystorePath, password string) (*bind.TransactOpts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthorizedTransactor", keystorePath, password)
	ret0, _ := ret[0].(*bind.TransactOpts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthorizedTransactor indicates an expected call of CreateAuthorizedTransactor.
func (mr *MockIDinClientMockRecorder) CreateAuthorizedTransactor(keystorePath, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthorizedTransactor", reflect.TypeOf((*MockIDinClient)(nil).CreateAuthorizedTransactor), keystorePath, password)
}

// GetAllNetworks mocks base method.
func (m *MockIDinClient) GetAllNetworks() ([]*Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNetworks")
	ret0, _ := ret[0].([]*Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNetworks indicates an expected call of GetAllNetworks.
func (mr *MockIDinClientMockRecorder) GetAllNetworks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNetworks", reflect.TypeOf((*MockIDinClient)(nil).GetAllNetworks))
}

// GetAllProviders mocks base method.
func (m *MockIDinClient) GetAllProviders() ([]*Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProviders")
	ret0, _ := ret[0].([]*Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProviders indicates an expected call of GetAllProviders.
func (mr *MockIDinClientMockRecorder) GetAllProviders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProviders", reflect.TypeOf((*MockIDinClient)(nil).GetAllProviders))
}

// GetAllProvidersByNetwork mocks base method.
func (m *MockIDinClient) GetAllProvidersByNetwork(networkURI string) ([]*Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProvidersByNetwork", networkURI)
	ret0, _ := ret[0].([]*Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProvidersByNetwork indicates an expected call of GetAllProvidersByNetwork.
func (mr *MockIDinClientMockRecorder) GetAllProvidersByNetwork(networkURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProvidersByNetwork", reflect.TypeOf((*MockIDinClient)(nil).GetAllProvidersByNetwork), networkURI)
}

// GetEthereumRpcClient mocks base method.
func (m *MockIDinClient) GetEthereumRpcClient() *ethclient.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEthereumRpcClient")
	ret0, _ := ret[0].(*ethclient.Client)
	return ret0
}

// GetEthereumRpcClient indicates an expected call of GetEthereumRpcClient.
func (mr *MockIDinClientMockRecorder) GetEthereumRpcClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEthereumRpcClient", reflect.TypeOf((*MockIDinClient)(nil).GetEthereumRpcClient))
}

// GetNetworkByName mocks base method.
func (m *MockIDinClient) GetNetworkByName(networkURI string) (*Network, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkByName", networkURI)
	ret0, _ := ret[0].(*Network)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkByName indicates an expected call of GetNetworkByName.
func (mr *MockIDinClientMockRecorder) GetNetworkByName(networkURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkByName", reflect.TypeOf((*MockIDinClient)(nil).GetNetworkByName), networkURI)
}

// GetProviderByAddress mocks base method.
func (m *MockIDinClient) GetProviderByAddress(providerAddress common.Address) (*Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderByAddress", providerAddress)
	ret0, _ := ret[0].(*Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProviderByAddress indicates an expected call of GetProviderByAddress.
func (mr *MockIDinClientMockRecorder) GetProviderByAddress(providerAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderByAddress", reflect.TypeOf((*MockIDinClient)(nil).GetProviderByAddress), providerAddress)
}

// GetRegistryData mocks base method.
func (m *MockIDinClient) GetRegistryData() (*DinRegistryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryData")
	ret0, _ := ret[0].(*DinRegistryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistryData indicates an expected call of GetRegistryData.
func (mr *MockIDinClientMockRecorder) GetRegistryData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryData", reflect.TypeOf((*MockIDinClient)(nil).GetRegistryData))
}

// RemoveProvider mocks base method.
func (m *MockIDinClient) RemoveProvider(auth *bind.TransactOpts, providerAddr common.Address) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveProvider", auth, providerAddr)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveProvider indicates an expected call of RemoveProvider.
func (mr *MockIDinClientMockRecorder) RemoveProvider(auth, providerAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveProvider", reflect.TypeOf((*MockIDinClient)(nil).RemoveProvider), auth, providerAddr)
}

// SetNetworkConfig mocks base method.
func (m *MockIDinClient) SetNetworkConfig(authTransactor *bind.TransactOpts, networkURI string, newConfig NetworkOperationsConfig) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNetworkConfig", authTransactor, networkURI, newConfig)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNetworkConfig indicates an expected call of SetNetworkConfig.
func (mr *MockIDinClientMockRecorder) SetNetworkConfig(authTransactor, networkURI, newConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNetworkConfig", reflect.TypeOf((*MockIDinClient)(nil).SetNetworkConfig), authTransactor, networkURI, newConfig)
}

// SetNetworkStatus mocks base method.
func (m *MockIDinClient) SetNetworkStatus(auth *bind.TransactOpts, networkURI string, networkStatus NetworkStatus) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNetworkStatus", auth, networkURI, networkStatus)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNetworkStatus indicates an expected call of SetNetworkStatus.
func (mr *MockIDinClientMockRecorder) SetNetworkStatus(auth, networkURI, networkStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNetworkStatus", reflect.TypeOf((*MockIDinClient)(nil).SetNetworkStatus), auth, networkURI, networkStatus)
}

// SetProviderStatus mocks base method.
func (m *MockIDinClient) SetProviderStatus(authTransactor *bind.TransactOpts, providerAddr common.Address, providerStatus ProviderStatus) (*types.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProviderStatus", authTransactor, providerAddr, providerStatus)
	ret0, _ := ret[0].(*types.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetProviderStatus indicates an expected call of SetProviderStatus.
func (mr *MockIDinClientMockRecorder) SetProviderStatus(authTransactor, providerAddr, providerStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProviderStatus", reflect.TypeOf((*MockIDinClient)(nil).SetProviderStatus), authTransactor, providerAddr, providerStatus)
}
