// Code generated by MockGen. DO NOT EDIT.
// Source: ./lib/watcherscore/interface.go
//
// Generated by this command:
//
//	mockgen -source=./lib/watcherscore/interface.go -package=watcherscore -destination=./lib/watcherscore/interface_mock.go
//

// Package watcherscore is a generated GoMock package.
package watcherscore

import (
	reflect "reflect"
	time "time"

	watcher "github.com/DIN-center/din-sc/apps/din-go/lib/watcher"
	gomock "go.uber.org/mock/gomock"
)

// MockIWatcherScoreManager is a mock of IWatcherScoreManager interface.
type MockIWatcherScoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockIWatcherScoreManagerMockRecorder
	isgomock struct{}
}

// MockIWatcherScoreManagerMockRecorder is the mock recorder for MockIWatcherScoreManager.
type MockIWatcherScoreManagerMockRecorder struct {
	mock *MockIWatcherScoreManager
}

// NewMockIWatcherScoreManager creates a new mock instance.
func NewMockIWatcherScoreManager(ctrl *gomock.Controller) *MockIWatcherScoreManager {
	mock := &MockIWatcherScoreManager{ctrl: ctrl}
	mock.recorder = &MockIWatcherScoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWatcherScoreManager) EXPECT() *MockIWatcherScoreManagerMockRecorder {
	return m.recorder
}

// AddNetworkFormula mocks base method.
func (m *MockIWatcherScoreManager) AddNetworkFormula(network string, formula ScoreFormula) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddNetworkFormula", network, formula)
}

// AddNetworkFormula indicates an expected call of AddNetworkFormula.
func (mr *MockIWatcherScoreManagerMockRecorder) AddNetworkFormula(network, formula any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNetworkFormula", reflect.TypeOf((*MockIWatcherScoreManager)(nil).AddNetworkFormula), network, formula)
}

// AddNetworkWithBuiltInFormula mocks base method.
func (m *MockIWatcherScoreManager) AddNetworkWithBuiltInFormula(network string, client watcher.IWatcherAPIClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNetworkWithBuiltInFormula", network, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNetworkWithBuiltInFormula indicates an expected call of AddNetworkWithBuiltInFormula.
func (mr *MockIWatcherScoreManagerMockRecorder) AddNetworkWithBuiltInFormula(network, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNetworkWithBuiltInFormula", reflect.TypeOf((*MockIWatcherScoreManager)(nil).AddNetworkWithBuiltInFormula), network, client)
}

// ComputeScores mocks base method.
func (m *MockIWatcherScoreManager) ComputeScores() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ComputeScores")
}

// ComputeScores indicates an expected call of ComputeScores.
func (mr *MockIWatcherScoreManagerMockRecorder) ComputeScores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeScores", reflect.TypeOf((*MockIWatcherScoreManager)(nil).ComputeScores))
}

// GetAllScores mocks base method.
func (m *MockIWatcherScoreManager) GetAllScores(network string) map[string]*Score {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllScores", network)
	ret0, _ := ret[0].(map[string]*Score)
	return ret0
}

// GetAllScores indicates an expected call of GetAllScores.
func (mr *MockIWatcherScoreManagerMockRecorder) GetAllScores(network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllScores", reflect.TypeOf((*MockIWatcherScoreManager)(nil).GetAllScores), network)
}

// GetNetworkFormula mocks base method.
func (m *MockIWatcherScoreManager) GetNetworkFormula(network string) *ScoreFormula {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetworkFormula", network)
	ret0, _ := ret[0].(*ScoreFormula)
	return ret0
}

// GetNetworkFormula indicates an expected call of GetNetworkFormula.
func (mr *MockIWatcherScoreManagerMockRecorder) GetNetworkFormula(network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkFormula", reflect.TypeOf((*MockIWatcherScoreManager)(nil).GetNetworkFormula), network)
}

// GetScore mocks base method.
func (m *MockIWatcherScoreManager) GetScore(network, providerID string) *Score {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScore", network, providerID)
	ret0, _ := ret[0].(*Score)
	return ret0
}

// GetScore indicates an expected call of GetScore.
func (mr *MockIWatcherScoreManagerMockRecorder) GetScore(network, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScore", reflect.TypeOf((*MockIWatcherScoreManager)(nil).GetScore), network, providerID)
}

// RemoveNetwork mocks base method.
func (m *MockIWatcherScoreManager) RemoveNetwork(network string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveNetwork", network)
}

// RemoveNetwork indicates an expected call of RemoveNetwork.
func (mr *MockIWatcherScoreManagerMockRecorder) RemoveNetwork(network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNetwork", reflect.TypeOf((*MockIWatcherScoreManager)(nil).RemoveNetwork), network)
}

// StartPeriodicUpdates mocks base method.
func (m *MockIWatcherScoreManager) StartPeriodicUpdates(frequency time.Duration) chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartPeriodicUpdates", frequency)
	ret0, _ := ret[0].(chan struct{})
	return ret0
}

// StartPeriodicUpdates indicates an expected call of StartPeriodicUpdates.
func (mr *MockIWatcherScoreManagerMockRecorder) StartPeriodicUpdates(frequency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPeriodicUpdates", reflect.TypeOf((*MockIWatcherScoreManager)(nil).StartPeriodicUpdates), frequency)
}
