name: e2e Caddy Integration Test

'on':
  pull_request:

jobs:
    test-caddy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            # - name: Authenticate with GitHub and Clone Private Repo
            #   env:
            #     TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token from GitHub Secrets
            #   run: |
            #     git config --global url."https://$TOKEN:@github.com/".insteadOf "https://github.com/"
            #     git clone https://github.com/DIN-center/din-sc.git

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.21'
            
            - name: Install xcaddy
              run: |
                export GOBIN=$HOME/go/bin
                go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

            - name: Use Custom Caddyfile and Run Caddy
              run: |
                GOPRIVATE=github.com/DIN-center $HOME/go/bin/xcaddy start --config ./.github/workflows/e2e_integration_test/Caddyfile
              shell: bash

            - name: Make the script executable
              run: chmod +x ./.github/workflows/e2e_integration_test/send_requests.sh

            - name: Send test requests
              run: |
                ./.github/workflows/e2e_integration_test/send_requests.sh
              shell: bash
              
            - name: Stop Caddy server
              run: |
               GOPRIVATE=github.com/DIN-center $HOME/go/bin/xcaddy stop
              shell: bash