// Code generated by MockGen. DO NOT EDIT.
// Source: ./cli/cmd/interface.go
//
// Generated by this command:
//
//	mockgen -source=./cli/cmd/interface.go -package=dincli -destination=./cli/cmd/interface_mock.go
//

// Package dincli is a generated GoMock package.
package dincli

import (
	reflect "reflect"

	din "github.com/DIN-center/din-sc/apps/din-go/lib/din"
	gomock "go.uber.org/mock/gomock"
)

// MockIOutputFormatter is a mock of IOutputFormatter interface.
type MockIOutputFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockIOutputFormatterMockRecorder
	isgomock struct{}
}

// MockIOutputFormatterMockRecorder is the mock recorder for MockIOutputFormatter.
type MockIOutputFormatterMockRecorder struct {
	mock *MockIOutputFormatter
}

// NewMockIOutputFormatter creates a new mock instance.
func NewMockIOutputFormatter(ctrl *gomock.Controller) *MockIOutputFormatter {
	mock := &MockIOutputFormatter{ctrl: ctrl}
	mock.recorder = &MockIOutputFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOutputFormatter) EXPECT() *MockIOutputFormatterMockRecorder {
	return m.recorder
}

// FormatNetwork mocks base method.
func (m *MockIOutputFormatter) FormatNetwork(network *din.Network, options FormatOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatNetwork", network, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormatNetwork indicates an expected call of FormatNetwork.
func (mr *MockIOutputFormatterMockRecorder) FormatNetwork(network, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatNetwork", reflect.TypeOf((*MockIOutputFormatter)(nil).FormatNetwork), network, options)
}

// FormatNetworks mocks base method.
func (m *MockIOutputFormatter) FormatNetworks(networks []*din.Network, options FormatOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatNetworks", networks, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormatNetworks indicates an expected call of FormatNetworks.
func (mr *MockIOutputFormatterMockRecorder) FormatNetworks(networks, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatNetworks", reflect.TypeOf((*MockIOutputFormatter)(nil).FormatNetworks), networks, options)
}

// FormatProvider mocks base method.
func (m *MockIOutputFormatter) FormatProvider(provider *din.Provider, options FormatOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatProvider", provider, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormatProvider indicates an expected call of FormatProvider.
func (mr *MockIOutputFormatterMockRecorder) FormatProvider(provider, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatProvider", reflect.TypeOf((*MockIOutputFormatter)(nil).FormatProvider), provider, options)
}

// FormatProviders mocks base method.
func (m *MockIOutputFormatter) FormatProviders(providers []*din.Provider, options FormatOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatProviders", providers, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// FormatProviders indicates an expected call of FormatProviders.
func (mr *MockIOutputFormatterMockRecorder) FormatProviders(providers, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatProviders", reflect.TypeOf((*MockIOutputFormatter)(nil).FormatProviders), providers, options)
}

// MockIFeesEstimator is a mock of IFeesEstimator interface.
type MockIFeesEstimator struct {
	ctrl     *gomock.Controller
	recorder *MockIFeesEstimatorMockRecorder
	isgomock struct{}
}

// MockIFeesEstimatorMockRecorder is the mock recorder for MockIFeesEstimator.
type MockIFeesEstimatorMockRecorder struct {
	mock *MockIFeesEstimator
}

// NewMockIFeesEstimator creates a new mock instance.
func NewMockIFeesEstimator(ctrl *gomock.Controller) *MockIFeesEstimator {
	mock := &MockIFeesEstimator{ctrl: ctrl}
	mock.recorder = &MockIFeesEstimatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFeesEstimator) EXPECT() *MockIFeesEstimatorMockRecorder {
	return m.recorder
}

// EstimateFees mocks base method.
func (m *MockIFeesEstimator) EstimateFees() (FeeData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateFees")
	ret0, _ := ret[0].(FeeData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateFees indicates an expected call of EstimateFees.
func (mr *MockIFeesEstimatorMockRecorder) EstimateFees() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateFees", reflect.TypeOf((*MockIFeesEstimator)(nil).EstimateFees))
}
